# Serverless definition file
# --------------------------
# Defines Lambda functions to be deployed to AWS using the Serverless Framework.
# http://serverless.com
#
# This creates an API which proxies to lambda

service: lambda-scraper

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  memorySize: 512
  timeout: 20

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
